// Resource header file generated by GRC utility

#ifndef GRCRES_HEADER_INCLUDED
#define GRCRES_HEADER_INCLUDED

#define PAL_MAIN                        0
#define PAL_SPLASH                      1
#define FNT_TITLE                       2
#define FNT_NAMES                       3
#define FNT_WNDTXT                      4
#define FNT_WNDTXTHIL                   5
#define FNT_WNDTXTDIM                   6
#define FNT_SMALL                       7
#define WNDID_NEWGAME                   8
#define WNDID_MSGBOX                    9
#define WNDID_NETWORKA                  10
#define WNDID_NETWORKB                  11
#define XMP_SPLASH                      12
#define XMP_ITEMS                       13
#define XMP_BOARD                       14
#define XMP_EXPLODE                     15
#define XMP_SELECT                      16
#define XMP_DICE                        17
#define XMP_MENUS                       18
#define XAV_ERROR                       19
#define XAV_EXPLODE                     20
#define XAV_FREE                        21
#define XAV_RISE                        22
#define XAV_SELECT                      23
#define XAV_SINK                        24
#define XAV_NONO                        25
#define XAV_MENUHIDE                    26
#define XAV_MENUSHOW                    27
#define XAV_CWITHIN                     28
#define BIN_TRACKS                      29

#endif // #ifndef GRCRES_HEADER_INCLUDED