// Resource header file generated by GRC utility

#ifndef GRCRES_HEADER_INCLUDED
#define GRCRES_HEADER_INCLUDED

#define PAL_MAIN                        0
#define PAL_SPLASH                      1
#define XMP_SPLASH                      2
#define XMP_ITEMS                       3
#define XMP_BOARD                       4
#define XMP_MARBLES                     5
#define XMP_HOLES                       6
#define XMP_EXPLODE                     7
#define XMP_SELECT                      8
#define XMP_DICE                        9
#define XMP_SMENU                       10
#define XMP_MENUS                       11
#define XMP_PLAYERTYPE                  12
#define FNT_TITLE                       13
#define FNT_NAMES                       14
#define FNT_WNDTXT                      15
#define FNT_WNDTXTHIL                   16
#define FNT_WNDTXTDIM                   17
#define FNT_SMALL                       18
#define WNDID_MSGBOX                    19
#define WNDID_NEWGAME                   20
#define WNDID_CONNECT                   21
#define WNDID_STARTNET                  22
#define WNDID_LOAD                      23
#define WNDID_SAVE                      24
#define WNDID_HELP                      25
#define WNDID_MUSIC                     26
#define BIN_TRACKS                      27
#define XAV_CURWITHIN                   28
#define XAV_DEFAULT                     29
#define XAV_EXPLODE                     30
#define XAV_FREEMARBLE                  31
#define XAV_CANT                        32
#define XAV_SELECT                      33
#define XAV_SINK                        34
#define XAV_RISE                        35
#define XMP_HELP                        36
#define HELP_MAIN                       37
#define HELP_2                          38
#define HELP_3                          39
#define HELP_4                          40
#define HELP_5                          41
#define HELP_6                          42
#define HELP_7                          43
#define HELP_8                          44
#define XMP_LOADING                     45

#endif // #ifndef GRCRES_HEADER_INCLUDED